### ISSUE TITLE
Inconsistency in lambda in boot.glmnet

### ISSUE THREAD

**Issue by msmah** [pbreheny/hdrm#2]
Hello,
In boot.glmnet there are several issues regarding the value of lambda:
(1) The input argument "lambda" (line 15) is supposed to specify the values of the regularization parameter in regression, but in line 27, it is assigned to lambda.min.ratio.
(2) Lambda is generally supposed to be a vector of multiple choices, but here, it must be a single value (in order for line 28 to be valid).
Thanks

**Comment by pbreheny** [comment]
1. Good point -- thank you for bringing this to my attention. This is fixed in the most recent commit.
2. This is by design. It is too cumbersome to bootstrap the entire path in high dimensions. For example, if p=20000, then simply initializing the array to store the bootstrap samples requires 4 GB. So the design solution here was to restrict attention to a single lambda value. However, you could argue that I should provide the option to bootstrap the entire path, as that would be useful for smaller data sets.
